// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using restauranteAPI.Data;
using System;

namespace restauranteAPI.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20180204212537_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("restauranteAPI.Models.Prato", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NomePrato")
                        .IsRequired();

                    b.Property<double>("PrecoPrato");

                    b.Property<int>("RestauranteID");

                    b.HasKey("ID");

                    b.ToTable("Pratos");
                });

            modelBuilder.Entity("restauranteAPI.Models.Restaurante", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NomeRestaurante")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Restaurantes");
                });
#pragma warning restore 612, 618
        }
    }
}
